apiVersion: v1
kind: Service
metadata:
  name: {{ include "ninjam.fullname" . }}
  labels:
    {{- include "ninjam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: ninjam
      port: {{ .Values.service.port }}
      targetPort: 2049
      protocol: TCP
  selector:
    {{- include "ninjam.selectorLabels" . | nindent 4 }}
